# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be992f369dff08c68d20f0dc79efd51c4c22c2857c73ecfc29171aae67641966c32d906b33ba7356f71bb346111ec490ca1fa7c0527beecb4ac94bac04727b0

test:
  secret_key_base: 8a8ce52e1351643e0cf44c40a01db2aaa6e895b085555350cb64d3e07bbf7bd3949ac23ded2474a950a60ebac8fb6d79fa49ec38c68c60794513d65765284d75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
